import pandas as pd
import os
import shutil
from Bio import SeqIO
import argparse
import json
import subprocess

# Argument Parser 
parser = argparse.ArgumentParser(description="Process a file based in the barcode string.")
parser.add_argument('sample', type=str, help="The input fasta file to be processed")
parser.add_argument('clusters', type=str, help="The input uc file to be processed")
parser.add_argument('igcicle1', type=str, help="The input IgClicle 1 file")
parser.add_argument('igcicle2', type=str, help="The input IgClicle 2 file")
parser.add_argument('chain_type', type=str, help="The chain to be processed")
parser.add_argument('output', type=str, help="Processed output file")
args = parser.parse_args()

# Default Parameters
min_seqs_cluster = 6
cdr3_ident = 0.85
output = args.output
output_dir = "/".join(output.split("/")[0:-2])  # extract output directory or default to current directory
output_cdr3_clusters_dir = "%s/cdr3_clusters"%output_dir

#try:
#    os.makedirs(output_cdr3_clusters_dir)
#except FileExistsError:
#    shutil.rmtree(output_cdr3_clusters_dir)
#    os.makedirs(output_cdr3_clusters_dir)

news_clusters_dir = "%s/new_clusters"%output_dir
news_clusters_cdr3_dir = "%s/new_cdr3_clusters"%news_clusters_dir
news_final_clusters_dir = "%s/new_final_clusters"%news_clusters_dir

## Input Files ##
chain_type = args.chain_type # VH or VL chain type
# Consensus file
input_file = args.sample
original_consensus_file = input_file

# read igblast alignments file
igblast1 = pd.read_csv(args.igcicle1,sep="\t", low_memory=False)
igblast2 = pd.read_csv(args.igcicle2,sep="\t", low_memory=False)

igblast = pd.concat([igblast1, igblast2], axis=0)
igblast['sequence_id'] = igblast['sequence_id'].astype(str) + '-' + igblast['locus'].astype(str)

igblast = igblast.drop_duplicates(subset=['sequence_id', 'locus'], keep='first') # remove duplicates with same region VH or VL
igblast.to_csv('%s/igAll.csv'%os.path.dirname(args.igcicle1), index=False)

if chain_type == "VH":
    igblast = igblast[igblast['locus']=='IGH']
else:
    igblast = igblast[igblast['locus']!='IGH']

# Clusters File
clusters = pd.read_csv(args.clusters,sep="\t",header=None)

try: 
    os.makedirs("%s/clusters_consensus"%output_dir)
except FileExistsError:
    pass
    #shutil.rmtree("%s/clusters_consensus"%output_dir)
    #os.makedirs("%s/clusters_consensus"%output_dir)

# For each consensus generated by vsearch put consensus in a separated directory to be used as medaka draft
for rec in SeqIO.parse(original_consensus_file, "fasta"):
    SeqIO.write(rec, "%s/clusters_consensus/%s.fasta"%(output_dir,rec.id.split(";")[0].split("=")[-1]), "fasta")

# Create clusters directories 
#try:
#    os.makedirs(news_clusters_dir)
#    os.makedirs(news_clusters_cdr3_dir)
#    os.makedirs(news_final_clusters_dir)
#except FileExistsError:
#    shutil.rmtree(news_clusters_dir)
#    os.makedirs(news_clusters_dir)
#    os.makedirs(news_clusters_cdr3_dir)
#    os.makedirs(news_final_clusters_dir)

# Get clusters mapping using C for get each cluster respresentant sequence ID and H for the sequences in each cluster
match_id_clusters = clusters[clusters.iloc[:, 0] == "H"].iloc[:,8:]
filtered_clusters = clusters[clusters.iloc[:, 0] == "C"]
filtered_clusters = filtered_clusters[filtered_clusters[2] > min_seqs_cluster]
filtered_clusters = filtered_clusters.sort_values(by=2, ascending=False)
print("First file Clusterized Ordened By clusters lenght: \n%s"%filtered_clusters)

## cluster seq to original id ##
cluster_seq_id = {
    "cluster": [],
    "seq":[]
}

for clus_id in filtered_clusters[8]:
    seqs_clus = match_id_clusters[match_id_clusters[9] == clus_id][8]
    merge_clus_ig = pd.merge(seqs_clus, igblast, left_on=8, right_on='sequence_id', how='inner')
    output_cdrs_file = open("%s/%s.fasta"%(output_cdr3_clusters_dir,clus_id),"w")
    for rec in merge_clus_ig.iloc:
        output_cdrs_file.write(">%s\n%s\n"%(rec["sequence_id"], rec["cdr3"]))
        cluster_seq_id["cluster"].append(clus_id)
        cluster_seq_id["seq"].append(rec["sequence_id"])

    output_cdrs_file.close()

filename = "%s/cluster_seq_id.json" %(output_cdr3_clusters_dir)

# Ensure the output directory exists
os.makedirs(output_cdr3_clusters_dir, exist_ok=True)

existing_data = {} # Default to an empty dictionary

# Try to load existing data from the JSON file
try:
    # Open file for reading ('r') with utf-8 encoding
    with open(filename, 'r', encoding='utf-8') as f:
        existing_data = json.load(f)
        # Basic check: ensure loaded data is a dictionary
        if not isinstance(existing_data, dict):
            print(f"Warning: File '{filename}' did not contain a dictionary. Overwriting.")
            existing_data = {}
except FileNotFoundError:
    # File doesn't exist yet, fine to proceed with empty existing_data
    print(f"File '{filename}' not found. Creating a new one.")
    pass
except json.JSONDecodeError:
    # File exists but contains invalid JSON
    print(f"Warning: Error decoding JSON from '{filename}'. Overwriting.")
    existing_data = {} # Reset to empty

# Update the existing data with the new data from cluster_seq_id
# Existing keys will be updated, new keys will be added.
for key, value in cluster_seq_id.items():
    if key in existing_data:
        existing_data[key].extend(value)
    else:
        existing_data[key] = value

# Write the combined data back to the file (overwriting the original)
try:
    # Open the file for writing ('w')
    with open(filename, 'w', encoding='utf-8') as f:
        # Use ensure_ascii=False for direct non-ASCII char support
        json.dump(existing_data, f, indent=4, ensure_ascii=False)
    print(f"Data successfully updated in '{filename}'")
except IOError as e:
    print(f"Error writing to file '{filename}': {e}")

