import pandas as pd
import numpy as np
import glob

# Load configuration
configfile: "config.yaml"

# Directories
OUTPUT_DIR="results"
IGCICLE_DIR="results/igcicle"
CLUSTERING_DIR="results/clustering"
CLUSTERING_RAW=f"{CLUSTERING_DIR}/raw"
CLUSTERING_CDR=f"{CLUSTERING_DIR}/cdr"
LOG_DIR="logs"

# Define script and Conda environment based on sequencing type
pre_process_illumina_script = "scripts/preProcess/preProcess_illumina.bash"
pre_process_nano_script = "scripts/preProcess/preProcess_nanopore.bash"
igcicle_script = "scripts/preProcess/igCicle.py"
clusterCdr3_script = "scripts/preProcess/cluster_cdr3.bash"
#cdrCluster_script = "scripts/preProcess/createCDR3Clusters.py"
map_clusters = "scripts/preProcess/mapClusters.py"
pre_process_env = "envs/preProcess.yaml"
igblast_env = "envs/igblast.yaml"
vsearch_env = "envs/vsearch.yaml"
medaka_env = "envs/medaka.yaml"

# get the list of columns from the input file
SAMPLES_DF=pd.read_csv(config["input"], sep=",")

# Create a dictionary to map sample names to their corresponding columns
sample_info=SAMPLES_DF.set_index('samples').T.to_dict()
samples=SAMPLES_DF['samples'].tolist()
ch_types=SAMPLES_DF['ch_type'].tolist()

rule all:
    input:
        expand(f"{OUTPUT_DIR}/quality_trimmed/{{sample}}/qc.fasta", sample=samples), # quality trimmed
        expand(f"{IGCICLE_DIR}/{{sample}}/VH_seqs.fasta", sample=samples), # IGCICLE VH
        expand(f"{IGCICLE_DIR}/{{sample}}/VL_seqs.fasta", sample=samples),  # IGCICLE VL
        expand(f"{IGCICLE_DIR}/{{sample}}/1_igCicle.tsv", sample=samples), # IGCICLE 1
        expand(f"{IGCICLE_DIR}/{{sample}}/2_igCicle.tsv", sample=samples),  # IGCICLE 2
        expand(f"{CLUSTERING_RAW}/{{sample}}/VH_clusters.uc", sample=samples), # VH clustering
        expand(f"{CLUSTERING_RAW}/{{sample}}/VL_clusters.uc", sample=samples),  # VL clustering
        expand(f"{CLUSTERING_CDR}/{{sample}}/cdr3_clusters/done.txt", sample=samples), # cdr3 mapping
        expand(f"{CLUSTERING_CDR}/{{sample}}/new_clusters/new_cdr3_clusters/done.txt", sample=samples) # cdr3 clustering

rule qualityTrimming:
    conda:
        pre_process_env
    input:
        file_1=lambda wildcards: sample_info[wildcards.sample]["file_1"]
    output:
        fq=f"{OUTPUT_DIR}/quality_trimmed/{{sample}}/qc.fastq",
        fa=f"{OUTPUT_DIR}/quality_trimmed/{{sample}}/qc.fasta"
    params:
        file_2=lambda wildcards: sample_info[wildcards.sample]["file_2"],
        generation=lambda wildcards: sample_info[wildcards.sample]["generation"]
    log:
        f"{LOG_DIR}/quality_trimmed/{{sample}}/trimming.log"
    shell:
        """
        # second generation 
        if [[ {params.generation} == "second" ]]; then
            {pre_process_illumina_script} {input.file_1} {params.file_2} {output.fq} >> {log} 2>&1

        # third generation
        else
            NanoFilt {input.file_1} -q 8 -l 2800 > {output.fq}
        fi

        # rename the fasta file
        TEMP_FASTA=$(mktemp)
        RENAMED_FASTA="{output.fa}"
        awk 'NR%4==1 {{printf(">%s\\n", substr($0, 2)); next}} NR%4==2 {{print}}' {output.fq} > "$TEMP_FASTA"

        if [[ {config[rename_reads]} == "True" ]]; then
            python scripts/preProcess/fasta_rename_id.py "$TEMP_FASTA" "{output.fa}"
        else
            mv "$TEMP_FASTA" "{output.fa}"
        fi
        """

# run IgCicle (multiple igblastn cicles)
rule igAnnotate:
    conda:
        igblast_env
    input:
        f"results/quality_trimmed/{{sample}}/qc.fasta"
    output:
        vh=f"{IGCICLE_DIR}/{{sample}}/VH_seqs.fasta",
        vl=f"{IGCICLE_DIR}/{{sample}}/VL_seqs.fasta",
        igcicle1=f"{IGCICLE_DIR}/{{sample}}/1_igCicle.tsv",
        igcicle2=f"{IGCICLE_DIR}/{{sample}}/2_igCicle.tsv"
    params:
        generation=lambda wildcards: sample_info[wildcards.sample]["generation"]
    log:
        f"{LOG_DIR}/igcicle/{{sample}}/igCicle.log"
    shell:
        """
        python3 {igcicle_script} {input} {output.vh} {output.vl} >> {log} 2>&1
        """

rule rawClustering:
    conda:
        medaka_env
    input:
        vh=f"{IGCICLE_DIR}/{{sample}}/VH_seqs.fasta",
        vl=f"{IGCICLE_DIR}/{{sample}}/VL_seqs.fasta"
    output:
        vh_uc=f"{CLUSTERING_RAW}/{{sample}}/VH_clusters.uc",
        vl_uc=f"{CLUSTERING_RAW}/{{sample}}/VL_clusters.uc",
        vh_cons=f"{CLUSTERING_RAW}/{{sample}}/VH_consensus.fasta",
        vl_cons=f"{CLUSTERING_RAW}/{{sample}}/VL_consensus.fasta"
    log:
        f"{LOG_DIR}/clustering/raw/{{sample}}/clustering.log"
    shell:
        """
        vsearch --cluster_fast {input.vh} --id 0.75 --uc {output.vh_uc} \
            --target_cov 0.9 --minqt 0.9 --consout {output.vh_cons} >> {log} 2>&1
        
        vsearch --cluster_fast {input.vl} --id 0.75 --uc {output.vl_uc} \
            --target_cov 0.9 --minqt 0.9 --consout {output.vl_cons} >> {log} 2>&1
        """

rule mapClusters:
    conda:
        medaka_env
    input:
        vh_fa=f"{CLUSTERING_RAW}/{{sample}}/VH_consensus.fasta",
        vl_fa=f"{CLUSTERING_RAW}/{{sample}}/VL_consensus.fasta",
        vh_uc=f"{CLUSTERING_RAW}/{{sample}}/VH_clusters.uc",
        vl_uc=f"{CLUSTERING_RAW}/{{sample}}/VL_clusters.uc",
        igcicle_1=f"{IGCICLE_DIR}/{{sample}}/1_igCicle.tsv",
        igcicle_2=f"{IGCICLE_DIR}/{{sample}}/2_igCicle.tsv"
    output:
        f"{CLUSTERING_CDR}/{{sample}}/cdr3_clusters/done.txt"
    log:
        f"{LOG_DIR}/clustering/cdr/{{sample}}/clustering.log"
    shell:
        """
        # process VH
        python3 {map_clusters} {input.vh_fa} {input.vh_uc} {input.igcicle_1} \
            {input.igcicle_2} VH {output} >> {log} 2>&1 

        # process VL
        python3 {map_clusters} {input.vl_fa} {input.vl_uc} {input.igcicle_1} \
            {input.igcicle_2} VL {output} >> {log} 2>&1

        output_dir=$(dirname {output})
        ls $output_dir/*.fasta > {output}
        """

rule cdrClustering:
    conda:
        vsearch_env
    input:
        file_list=f"{CLUSTERING_CDR}/{{sample}}/cdr3_clusters/done.txt",
    output:
        done=f"{CLUSTERING_CDR}/{{sample}}/new_clusters/new_cdr3_clusters/done.txt"
    log:
        f"{LOG_DIR}/clustering/cdr/{{sample}}/new_clusters/new_cdr3_clusters/cdr_clustering.log"
    shell:
        """
        {clusterCdr3_script} {input.file_list} {output.done} >> {log} 2>&1
        """